### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by rafaelscbr** [felipenmoura/sos-stackoverflow-search#1]
Realizei a instalação conforme orientado no Readme, quando executo o comando ele me retorna : 

`/usr/local/lib/node_modules/so-search/dist/sos.js:9
    return new Promise(function (resolve, reject) {
               ^

ReferenceError: Promise is not defined
    at Object.showQuestions (/usr/local/lib/node_modules/so-search/dist/sos.js:9:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/so-search/index.js:9:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`

**Comment by felipenmoura** [comment]
hm, estranho. Aparentemente a versão do node que tu está usando não tem suporte nativo a Promises.
Qual a versão do node que tu está usando?
`node --version`

Posso colocar um shim para promises ali, dai resolve isto e passamos a ter suporte para versões anteriores.

**Comment by rafaelscbr** [comment]
Minha versão : v0.10.25

EDIT:
Atualizei aqui e funciono corretamente, mas acho bacana a ideia do shim, assim passamos a ter suporte para versões anteriores.

**Comment by felipenmoura** [comment]
Excelente, Rafael.
Acho que é uma boa mesmo usar um shim!
Assim que tiver tempo eu faço isto, ou se preferir pode enviar uma pull request :)
